version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: zxcvb
      POSTGRES_DB: postgres
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-business-backend
    command: >
      bash -c "alembic upgrade head && 
      uvicorn src.main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
    depends_on:
          - db
volumes:
  postgres_data: