"""empty message

Revision ID: 4efe1997880c
Revises: e9033059b3d8
Create Date: 2025-01-24 14:28:28.850070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4efe1997880c'
down_revision: Union[str, None] = 'e9033059b3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_info')

    # Создаём заново таблицу users_info с нужными колонками
    op.create_table(
        'users_info',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('login', sa.String(length=20), index=True, unique=True),
        sa.Column('password', sa.String(length=20)),
        sa.Column('email', sa.String(length=20), unique=True),
        sa.Column('age', sa.Integer(), nullable=False),
        sa.Column('male', sa.String(length=20), nullable=False),
        sa.Column('city', sa.String(length=20), nullable=False),
        sa.Column('registrated_at', sa.DateTime(), default=sa.func.now(), index=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'email',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users_info', 'city')
    op.drop_column('users_info', 'male')
    op.drop_column('users_info', 'age')
    # ### end Alembic commands ###
