"""empty message

Revision ID: 93f1d4731e01
Revises: 36efbddc2395
Create Date: 2025-01-23 23:03:17.769321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93f1d4731e01'
down_revision: Union[str, None] = '36efbddc2395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_login_and_registrated_at', table_name='users_info')
    op.drop_table('users_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('login', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('registrated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_info_pkey'),
    sa.UniqueConstraint('login', 'email', name='users_info_login_email_key')
    )
    op.create_index('idx_login_and_registrated_at', 'users_info', ['login', 'registrated_at'], unique=False)
    # ### end Alembic commands ###
