"""empty message

Revision ID: af66f3799858
Revises: 4efe1997880c
Create Date: 2025-01-24 14:48:01.118795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af66f3799858'
down_revision: Union[str, None] = '4efe1997880c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_info', 'login',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users_info', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users_info', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_info', 'male',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users_info', 'city',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users_info', 'registrated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index('idx_login_and_registrated_at', 'users_info', ['login', 'registrated_at'], unique=False, postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_login_and_registrated_at', table_name='users_info', postgresql_using='btree')
    op.alter_column('users_info', 'registrated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users_info', 'city',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users_info', 'male',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users_info', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_info', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users_info', 'login',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
