"""empty message

Revision ID: e7f743503b6c
Revises: 70ebcec90e63
Create Date: 2025-01-23 23:15:58.277600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7f743503b6c'
down_revision: Union[str, None] = '70ebcec90e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_login_and_registrated_at', table_name='users_info')
    op.drop_index('ix_users_info_login', table_name='users_info')
    op.drop_index('ix_users_info_registrated_at', table_name='users_info')
    op.drop_table('users_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('login', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('registrated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('login', 'email', name='users_info_pkey')
    )
    op.create_index('ix_users_info_registrated_at', 'users_info', ['registrated_at'], unique=False)
    op.create_index('ix_users_info_login', 'users_info', ['login'], unique=False)
    op.create_index('idx_login_and_registrated_at', 'users_info', ['login', 'registrated_at'], unique=False)
    # ### end Alembic commands ###
