"""empty message

Revision ID: e9033059b3d8
Revises: e7f743503b6c
Create Date: 2025-01-23 23:20:29.054970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9033059b3d8'
down_revision: Union[str, None] = 'e7f743503b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('registrated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'login', 'email')
    )
    op.create_index('idx_login_and_registrated_at', 'users_info', ['login', 'registrated_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_users_info_login'), 'users_info', ['login'], unique=False)
    op.create_index(op.f('ix_users_info_registrated_at'), 'users_info', ['registrated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_info_registrated_at'), table_name='users_info')
    op.drop_index(op.f('ix_users_info_login'), table_name='users_info')
    op.drop_index('idx_login_and_registrated_at', table_name='users_info', postgresql_using='btree')
    op.drop_table('users_info')
    # ### end Alembic commands ###
