"""initial

Revision ID: 507734bff130
Revises: 
Create Date: 2025-01-28 00:54:54.199457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507734bff130'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('male', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=20), nullable=True),
    sa.Column('registrated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_email', 'users_info', ['email'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_users_info_login'), 'users_info', ['login'], unique=True)
    op.create_index(op.f('ix_users_info_registrated_at'), 'users_info', ['registrated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_info_registrated_at'), table_name='users_info')
    op.drop_index(op.f('ix_users_info_login'), table_name='users_info')
    op.drop_index('idx_email', table_name='users_info', postgresql_using='btree')
    op.drop_table('users_info')
    # ### end Alembic commands ###
